version: '3.8'
services:
    dershop-prometheus:
        image: prom/prometheus:v2.26.0
        volumes:
            - ./prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - 9090:9090
    dershop-grafana:
        image: grafana/grafana:7.5.2
        volumes:
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_INSTALL_PLUGINS=grafana-piechart-panel
        ports:
            - 3000:3000
