version: '3.8'
services:
    dershop-postgresql:
        container_name: dershop-postgresql
        image: postgres:13.2
        # volumes:
        #     - my_path/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_DB=dershop
            - POSTGRES_USER=dershop-user
            - POSTGRES_PASSWORD=
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
