name: gradle-build

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        # Service containers to run with `container-job`
        services:
            # Label used to access the service container
            postgres:
                # Docker Hub image
                image: postgres:13.2
                # Provide the password for postgres
                env:
                    POSTGRES_DB: dershop
                    POSTGRES_USER: dershop-user
                    POSTGRES_PASSWORD: postgres-pw
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v2
            - name: Update apt
              run: sudo apt-get update
            - name: Install graphviz
              run: sudo apt install graphviz libgraphviz-dev pkg-config
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Cache Gradle packages
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run: ./gradlew build jacocoTestReport
            - name: Copy all reports to docs dir for gh-pages
              run: mv -v ./build/reports/* ./build/asciidoc/html5
            - name: Cleanup Gradle Cache
                # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
                # Restoring these files from a GitHub Actions cache might cause problems for future builds.
              run: |
                  rm -f ~/.gradle/caches/modules-2/modules-2.lock
                  rm -f ~/.gradle/caches/modules-2/gc.properties
            - name: Deploy to GitHub Pages
              uses: Cecilapp/GitHub-Pages-deploy@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                email: hasan.selman.kara@gmai.com
                build_dir: build/asciidoc/html5
                jekyll: no
